name: 🛠 Техническая задача (Dev Task)
description: Создать задачу на разработку или доработку утилиты
title: "[Dev]: <Краткое название задачи>"
labels: ["enhancement", "wip"]
assignees:
  - Nurassyl28
body:
  - type: input
    id: feature_name
    attributes:
      label: Что нужно сделать?
      placeholder: Например: Добавить поддержку MOSS для антиплагиата
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Детали реализации
      description: Опишите технические детали, какие файлы нужно трогать.
      placeholder: |
        Нужно изменить файл main.py...
        Добавить новую функцию в autochecker/...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Приоритет
      options:
        - 🔥 High (Срочно)
        - 🟡 Medium (Обычный)
        - 🧊 Low (Может подождать)
    validations:
      required: true

  - type: checkboxes
    id: definition_of_done
    attributes:
      label: Критерии готовности (DoD)
      options:
        - label: Код написан и работает
        - label: Тесты проходят локально
        - label: Обновлен requirements.txt (если нужно)
