name: Bug Report Simple
description: Сообщить об ошибке (тестовая версия)
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "### Спасибо, что нашли баг!"

  - type: textarea
    id: description
    attributes:
      label: Описание проблемы
      description: Что пошло не так?
      placeholder: Опишите ошибку здесь...
    validations:
      required: true
