name: 🛠 Техническая задача (Dev Task)
description: Создать задачу с полным описанием, приоритетом и чек-листом
title: "[Dev]: "
labels: ["enhancement", "wip"]
body:
  - type: input
    id: feature_name
    attributes:
      label: Что нужно сделать? (Коротко)
      placeholder: Например: Добавить проверку на плагиат
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Детали реализации
      description: Опишите, как это должно работать технически.
      placeholder: В файле main.py нужно изменить функцию...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Приоритет
      options:
        - 🔥 High (Срочно)
        - 🟡 Medium (Обычный)
        - 🧊 Low (Не горит)
    validations:
      required: true

  - type: checkboxes
    id: dod
    attributes:
      label: Критерии готовности (Definition of Done)
      options:
        - label: Код написан
        - label: Локальные тесты пройдены
        - label: Документация обновлена
